apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod-reader
  namespace: ashu-developer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
